### ISSUE TITLE
Broken in 3.2.4rc5

### ISSUE THREAD

**Issue by Yavmarto** [Shin-NiL/Godot-Android-Share-Plugin#14]
Hello Shin-Nil
Thank you for this plugin it worked perfectly up until 3.2.3

In the current 3.2.4rc5 it crashes the game:

I get the following verifying issue:

Process: org.godotengine.godotshareplugindemo, PID: 4359
    java.lang.VerifyError: Verifier rejected class shinnil.godot.plugin.android.godotshare.GodotShare: void shinnil.godot.plugin.android.godotshare.GodotShare.<init>(org.godotengine.godot.Godot) failed to verify: void shinnil.godot.plugin.android.godotshare.GodotShare.<init>(org.godotengine.godot.Godot): [0x3] register v1 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'shinnil.godot.plugin.android.godotshare.GodotShare' appears in /data/app/org.godotengine.godotshareplugindemo-XnxD3cM0rN41nFCNJgobjg==/base.apk)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:141)
        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:63)
        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:95)
        at org.godotengine.godot.Godot.onCreate(Godot.java:585)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2414)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2243)
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:654)
        at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:61)
        at com.godot.game.GodotApp.onCreate(GodotApp.java:46)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2022)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:359)
        at android.app.ActivityThread.main(ActivityThread.java:7418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

Do you have any idea how to solve this?

**Comment by Shin-NiL** [comment]
I have to take a look at 3.2.4, but I'll do that once the stable version is released. The things are always changing in development.

**Comment by tpaulino7** [comment]
Hi, 
The crash is still there in the current stable 3.3 release
The plugin is great, an update for this version will be appreciated!

**Comment by PseudoC0de** [comment]
Still present in 3.3 stable, it crashes the app on startup.
This is the ADB error log.



`E AndroidRuntime: java.lang.VerifyError: Verifier rejected class shinnil.godot.plugin.android.godotshare.GodotShare: void shinnil.godot.plugin.android.godotshare.GodotShare.<init>(org.godotengine.godot.Godot) failed to verify: void shinnil.godot.plugin.android.godotshare.GodotShare.<init>(org.godotengine.godot.Godot): [0x3] register v1 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity`

**Comment by Shin-NiL** [comment]
New version published.
